config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :chapters
  resources :stories

  namespace :api do
    resources :stories do
      resources :chapters
    end
  end

  root 'sessions#new'

  get '/up' => 'chapters#up'
  get '/down' => 'chapters#down'

end

app/models/story.rb
# t.string   "title"
# t.text     "description"

class Story < ActiveRecord::Base
	has_many :chapters, ->() { order(position: :asc) }

	validates :title, :description, presence: true
	validates :title, uniqueness: true
	validates :description, :title, length: { minimum: 5 }


	def self.rearange_story_list(stories)

    stories.each_with_index do |story, index|
      story.position = index + 1
      story.save!
    end
  end
end

app/controllers/api/stories_controller.rb
class Api::StoriesController < ApplicationController
  skip_before_action :authorize
  skip_before_filter :verify_authenticity_token

  def index
    stories = Story.all
    render json: stories
  end

  def show
    story = Story.find(params[:id])
    render json: story
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: :index
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    # Story.rearange_chapter_list Story.all
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :description)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title ,{class: "form-control"}%>
  </div>
  <div class="form-group">
    <%= f.label :description %><br/>
    <%= f.text_area :description ,{class: "form-control"}%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Editing Story</h1>
  </div>
</div>

<div class="container">
  <%= render 'form' %>
  <br><br>
  <%= link_to 'Show', @story %> |
  <%= link_to 'Back', stories_path %>
</div>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <div class="container">
    <h1>Story List</h1>
  </div>
</div>
<div class="container">
  <p><%= link_to 'New Story', new_story_path %></p>
  <br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.description %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/stories/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>New Story</h1>
  </div>
</div>

<div class="container">

  <%= render 'form' %>
  <%= p "#{@chapters}" %>
  <br><br>
  <%= link_to 'Back', stories_path %>
</div>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>


<div class="jumbotron">
  <div class="container">
    <h1>Story Details</h1>

    <p>
      <strong>Title:</strong>
      <%= @story.title %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @story.description %>
    </p>
  </div>
</div>

<div class="container">
  <p><%= link_to 'New Chapter', new_chapter_path(story: @story.id) %></p>
  <br><br>
  <table class="table table-stripped">
    <thead>
      <tr>
        <th>Position</th>
        <th>Title</th>
        <th>Video</th>
        <th>Pdf</th>
        <th>Audio</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <%= render(@story.chapters) %>

</table>
<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>
</div>