config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :chapters
  resources :stories

  namespace :api do
    resources :stories do
      resources :chapters
    end
  end

  root 'sessions#new'

  get '/up' => 'chapters#up'
  get '/down' => 'chapters#down'

end

app/models/chapter.rb
# t.string   "title"
# t.integer  "position"
# t.string   "video"
# t.string   "pdf"
# t.string   "audio"
# t.integer  "story_id"

class Chapter < ActiveRecord::Base

  belongs_to :story
# Think about how necessary it is to have uniqueness accross chapters
# for media_type
  validates :title, :position, :story,  presence: true

	validates :title, uniqueness: true
  validates_uniqueness_of :position, scope: :story

	validates :title, length: { minimum: 5 }
  validate :media_type

  # this breaks the ordering of chapters
  mount_uploader :video, VideoUploader
  mount_uploader :pdf, PdfUploader
  mount_uploader :audio, AudioUploader

  private
  def media_type
    unless video.present? ^ pdf.present? ^ audio.present?
      errors.add(:media_type, " At Least One media type is needed")
    end
  end


  def self.swap_position(chapter_a, chapter_b)
  	unless (chapter_a == nil or chapter_b == nil)
      @position_a = chapter_a.position
      @position_b = chapter_b.position
      chapter_a.position = chapter_a.story.chapters.count + 1
      chapter_a.save!(validate: false)
      chapter_b.position = @position_a
      chapter_b.save!(validate: false)
  		chapter_a.position = @position_b
  		chapter_a.save!(validate: false)
  	end
  end

  def self.get_chapter_above(chapter)
  	return chapter.story.chapters.find_by(position: chapter.position - 1)
  end

  def self.get_chapter_below(chapter)
  	return chapter.story.chapters.find_by(position: chapter.position + 1)
  end

  def self.rearange_chapter_list(chapters)

    chapters.each_with_index do |chapter, index|
      chapter.position = index + 1
      chapter.save!
    end
  end

end

app/controllers/api/chapters_controller.rb
class Api::ChaptersController < ApplicationController
  skip_before_action :authorize
  skip_before_filter :verify_authenticity_token

  def index
    chapters = Chapter.where(story_id: params[:story_id])
    render json: chapters
  end

  def show
    chapter = Chapter.where(id: params[:id], story_id: params[:story_id])
    render json: chapter
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: :index
  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
    #@chapters = Story.find(:story_id).chapters
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @back_to_begining_url = session[:my_previous_url]
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
    @stories = Story.all
  end

  def save_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
    session[:my_previous_url] = URI(request.referer || '').path
  end

  # GET /chapters/1/edit
  def edit
    @stories = Story.all
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @stories = Story.all
    @chapters = Chapter.all
    @chapter = Chapter.new(chapter_params)
    @chapter.position = @chapters.where(story: @chapter.story).count + 1

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    @stories = Story.all
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapters = Chapter.all.where(story: @chapter.story)
    @chapter.destroy
    Chapter.rearange_chapter_list @chapters
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def up
    chapter_a = Chapter.find(params[:chapter])
    chapter_b = Chapter.get_chapter_above chapter_a
    Chapter.swap_position(chapter_a, chapter_b)
    redirect_to chapter_a.story
  end

  def down
    chapter_a = Chapter.find(params[:chapter])
    chapter_b = Chapter.get_chapter_below chapter_a
    Chapter.swap_position(chapter_a, chapter_b)
    redirect_to chapter_a.story
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :position,
                                      :video, :pdf,
                                      :audio, :story_id)
    end

end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_chapter.html.erb
  <tbody>
      <tr>
        <td><%= chapter.position %></td>
        <td><%= chapter.title %></td>
        <td><%= chapter.video_identifier %></td>
        <td><%= chapter.pdf_identifier %></td>
        <td><%= chapter.audio_identifier %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Delete', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <% if Chapter.get_chapter_above chapter %>
            <%= link_to up_path(chapter: chapter), class: "btn btn-default" do %>
              &uarr;
            <% end %>
          <% end %>
          <% if Chapter.get_chapter_below chapter %>
            <%= link_to down_path(chapter: chapter), class: "btn btn-default" do %>
              &darr;
            <% end %>
          <% end %>
        </td>
      </tr>
  </tbody>

app/views/chapters/_form.html.erb
<%= form_for @chapter, html: {multipart: true} do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title ,{class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :video %><br>
    <%= f.file_field :video,{class: ""} %>
  </div>

  <div class="form-group">
    <%= f.label :pdf %><br>
    <%= f.file_field :pdf,{class: ""} %>
    <% #f.hidden_field :pdf_cache %>
  </div>

  <div class="form-group">
    <%= f.label :audio %><br>
    <%= f.file_field :audio,{class: ""} %>
  </div>


  <div class="form-group">
    <%= f.label :story %><br>
    <%= f.collection_select :story_id, @stories, :id, :title, {
      :selected => params[:story] }, {class: "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Editing Chapter</h1>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
  <br><br>
  <%= link_to 'Show', @chapter %> |
  <%= link_to 'Back', :back %>
</div>

app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <div class="container">
    <h1>Chapter List</h1>
  </div>
</div>



<div class="container">
  <p><%= link_to 'New Chapter', new_chapter_path %></p>
  <br>
  <br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Position</th>
      <th>Video</th>
      <th>Pdf</th>
      <th>Audio</th>
      <th>Story</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.title %></td>
        <td><%= chapter.position %></td>
        <td><%= chapter.video %></td>
        <td><%= chapter.pdf %></td>
        <td><%= chapter.audio %></td>
        <td><%= chapter.story.title %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/chapters/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>New Chapter</h1>
  </div>
</div>

<div class="container">
  <%= render 'form' %>

  <br><br>
  <%= link_to 'Back', :back %>
</div>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <div class="container">
    <h1><%= @chapter.title %> Chapter</h1>
  </div>
</div>


<div class="container">
  <table class="table table-stripped">
    <tr>
      <th>Titles</th>
      <th>Values</th>
    </tr>
    <tbody>
      <tr>
        <td>Position:</td>
        <td><%= @chapter.position %></td>
      </tr>
      <tr>
        <td>Video:</td>
        <td><%= @chapter.video %></td>
      </tr>
      <tr>
        <td>Pdf:</td>
        <td><%= @chapter.pdf %></td>
      </tr>
      <tr>
        <td>Audio:</td>
        <td><%= @chapter.audio %></td>
      </tr>
      <tr>
        <td>Story:</td>
        <td><%= @chapter.story.title %></td>
      </tr>
    </tbody>
  </table>


  <%= link_to 'Edit', edit_chapter_path(@chapter) %> |
  <%= link_to 'Back', @back_to_begining_url %>

</div>