config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :chapters
  resources :stories

  namespace :api do
    resources :stories do
      resources :chapters
    end
  end

  root 'sessions#new'

  get '/up' => 'chapters#up'
  get '/down' => 'chapters#down'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoMuseum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if session[:user_id] %>
          <li class="<% current_page?(stories_path)? 'active' : '' %>">
            <%= link_to 'Stories', stories_path %>
          </li>
          <li class="<% current_page?(chapters_path)? 'active' : '' %>">
            <%= link_to 'Chapters', chapters_path %>
          </li>
          <li>
            <%= link_to 'Manage Users', users_path %>
          </li>
          <li>
            <%= link_to 'Logout', logout_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
<%= yield %>

</body>
</html>